### ISSUE TITLE
Error when importing the custom extension in the Fuse Online project's connections

### ISSUE THREAD

**Issue by kun44l** [gpe-mw-training/fuse-ipaas-labs#2]
Hello,

As par of the Red Hat Fuse Online course (Red Hat Fuse 7 Foundations Part 1: Fuse Online)
I was trying to import the sysndesis-extension-custom-1.0.0.jar.

However, I noticed that the sysndesis server logged the following error:

io.syndesis.server.endpoint.v1.SyndesisRestException: An error has occurred while trying to process the technical extension. Please, check the input file. Cannot find manifest file (META-INF/syndesis/syndesis-extension-definition.json) inside JAR

Caused by: java.lang.IllegalArgumentException: Cannot find manifest file (META-INF/syndesis/syndesis-extension-definition.json) inside JAR
	at io.syndesis.extension.converter.DefaultBinaryExtensionAnalyzer.doGetExtension(DefaultBinaryExtensionAnalyzer.java:87) ~[extension-converter-1.9.0.fuse-760020-redhat-00001.jar!/:1.9.0.fuse-760020-redhat-00001]
	at io.syndesis.extension.converter.DefaultBinaryExtensionAnalyzer.getExtension(DefaultBinaryExtensionAnalyzer.java:52) ~[extension-converter-1.9.0.fuse-760020-redhat-00001.jar!/:1.9.0.fuse-760020-redhat-00001]
	at io.syndesis.server.endpoint.v1.handler.extension.ExtensionHandler.extractExtension(ExtensionHandler.java:292) ~[server-endpoint-1.9.0.fuse-760020-redhat-00001.jar!/:1.9.0.fuse-760020-redhat-00001]
	at io.syndesis.server.endpoint.v1.handler.extension.ExtensionHandler.upload(ExtensionHandler.java:133) ~[server-endpoint-1.9.0.fuse-760020-redhat-00001.jar!/:1.9.0.fuse-760020-redhat-00001]
	... 123 common frames omitted
	Suppressed: org.skife.jdbi.v2.exceptions.TransactionException: Failed to commit transaction
		at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.commit(LocalTransactionHandler.java:71) ~[jdbi-2.78.jar!/:2.78]
		at org.skife.jdbi.v2.BasicHandle.commit(BasicHandle.java:171) ~[jdbi-2.78.jar!/:2.78]
		at io.syndesis.server.filestore.impl.SqlFileStore$HandleCloserInputStream.close(SqlFileStore.java:356) ~[server-filestore-1.9.0.fuse-760020-redhat-00001.jar!/:1.9.0.fuse-760020-redhat-00001]
		at io.syndesis.server.endpoint.v1.handler.extension.ExtensionHandler.$closeResource(ExtensionHandler.java:293) ~[server-endpoint-1.9.0.fuse-760020-redhat-00001.jar!/:1.9.0.fuse-760020-redhat-00001]
		at io.syndesis.server.endpoint.v1.handler.extension.ExtensionHandler.extractExtension(ExtensionHandler.java:293) ~[server-endpoint-1.9.0.fuse-760020-redhat-00001.jar!/:1.9.0.fuse-760020-redhat-00001]
		... 124 common frames omitted
	Caused by: java.sql.SQLException: Connection is closed
		at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:489)
		at com.sun.proxy.$Proxy146.commit(Unknown Source)
		at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:361)
		at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
		at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.commit(LocalTransactionHandler.java:68)
		... 128 common frames omitted

Any idea on how to resolve this?
Thanks

**Comment by kun44l** [comment]
Can someone point me to the source code to build the syndesis-extension-custom-1.0.0.jar?
I can try to fix and build it locally.

Thanks,
Kunaal
